name: CI Workflow

on:
  push:
    branches:
    - dev

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
    - name: Execute Installer
      env:
        branch: ${{ github.ref_name }}
      run: |
        wget -O - https://raw.githubusercontent.com/uniquetrij/rosrc/${branch:-main}/ros-installer.sh | sh
    - name: Verify ROS 2 Installation
      if: false
      run: |
        if [ ! -z $(dpkg -l | grep ros-$(ls /opt/ros/) | wc -l) ]; then
          echo "Installation successful."
        else
          echo "Installation failed."
          exit 1
        fi
  #   - name: Verify Miniconda3 Installation
  #     run: |
  #       if [ ! -z "(conda -V)" ]; then
  #         echo "Miniconda3 installation successful."
  #       else
  #         echo "Miniconda3 installation failed."
  #         exit 1
  #       fi

  #   - name: Verify Python Venv Installation
  #     run: |
  #       if [ ! -z "$(conda activate $(ls /opt/ros/) && python -V)" ]; then
  #         echo "Python venv installation successful."
  #       else
  #         echo "Python venv installation failed."
  #         exit 1
  #       fi

  # merge:
  #   needs: install
  #   runs-on: ubuntu-24.04

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3

  #   - name: Configure Git
  #     run: |
  #       git config user.name "GitHub Actions"
  #       git config user.email "actions@github.com"

  #   - name: Merge dev into main
  #     run: |
  #       git checkout main
  #       git merge dev --no-ff -m "Merge dev into main via GitHub Actions"

  #   - name: Push Changes
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: |
  #       git push origin main
