name: CI Workflow

on:
  push:
    branches:
    - dev

jobs:
  install:
    runs-on: ubuntu-24.04

    steps:
    - name: Check
      run: |
        if [ "$GITHUB_ACTIONS" = "true" ]; then
          echo "Running in GitHub Actions workflow."
        else
          echo "Running locally."
        fi

        if "CI" not in os.environ or not os.environ["CI"] or "GITHUB_RUN_ID" not in os.environ:
            return False

        headers = {"Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"}
        url = f"https://api.github.com/repos/{os.environ['GITHUB_REPOSITORY']}/actions/runs/{os.environ['GITHUB_RUN_ID']}"
        response = requests.get(url, headers=headers)

        return response.status_code == 200 and "workflow_runs" in response.json()
  #   - name: Execute Installer
  #     run: |
  #       wget -O - https://raw.githubusercontent.com/uniquetrij/rosrc/${{ github.ref_name }}/ros-installer.sh | sh

  #   - name: Verify ROS 2 Installation
  #     if: false
  #     run: |
  #       if [ ! -z $(dpkg -l | grep ros-$(ls /opt/ros/) | wc -l) ]; then
  #         echo "Installation successful."
  #       else
  #         echo "Installation failed."
  #         exit 1
  #       fi

  #   - name: Verify Miniconda3 Installation
  #     run: |
  #       if [ ! -z "(conda -V)" ]; then
  #         echo "Miniconda3 installation successful."
  #       else
  #         echo "Miniconda3 installation failed."
  #         exit 1
  #       fi

  #   - name: Verify Python Venv Installation
  #     run: |
  #       if [ ! -z "$(conda activate $(ls /opt/ros/) && python -V)" ]; then
  #         echo "Python venv installation successful."
  #       else
  #         echo "Python venv installation failed."
  #         exit 1
  #       fi

  # merge:
  #   needs: install
  #   runs-on: ubuntu-24.04

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3

  #   - name: Configure Git
  #     run: |
  #       git config user.name "GitHub Actions"
  #       git config user.email "actions@github.com"

  #   - name: Merge dev into main
  #     run: |
  #       git checkout main
  #       git merge dev --no-ff -m "Merge dev into main via GitHub Actions"

  #   - name: Push Changes
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: |
  #       git push origin main
